apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clixx-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xtinead/clixx-gitops-platform.git
    targetRevision: main
    path: gitops/apps/overlays/prod/clixx
  destination:
    server: https://kubernetes.default.svc
    namespace: clixx-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
